#%RAML 1.0 DataType


properties:
  data:
    type: array
    items:
      type: !include site.raml
  limit:
    type: integer
    description: Maximum number of entries per page
    example: 10
  start:
    type: integer
    description: Starting page number, first page is 1
    example: 1
  total:
    type: integer
    description: Total number of users in the result
    example: 405