#%RAML 1.0 DataType

properties:
  healthy: 
    type: boolean
  uptime: 
    type: string
  pom_version:
    type: string
  env:
    type: string
  git_dirty:
    type: boolean
  git_branch:
    type: string
  git_commitSha:
    type: string